name: PHPStan static analyze

on: [push]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          args: --ignore-platform-reqs

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@master
        with:
          path: src/